// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qawafnrbqlgixfgsshec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhd2FmbnJicWxnaXhmZ3NzaGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMjk2NjUsImV4cCI6MjA1NzcwNTY2NX0.CPOgJSPH0PgTBBzv9siVkbpSjWce2b3uUaiDKGH9igQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);